### ISSUE TITLE
schematic_mode.py gives KeyError on "number_of_wheels"

### ISSUE THREAD

**Issue by Dreyevr** [HARPLab/DReyeVR#100]
When trying to launch schematic_mode, we get the following output:

Initializing DReyeVR ego vehicle as hero_actor
initialized DReyeVRSensor PythonAPI client
INFO:  Found the required file in cache!  Carla/Maps/TM/Town03.bin
Traceback (most recent call last):
  File "schematic_mode.py", line 96, in <module>
    main()
  File "C:\CarlaDReyeVR\carla\PythonAPI\examples\no_rendering_mode.py", line 1636, in main
    game_loop(args)
  File "C:\CarlaDReyeVR\carla\PythonAPI\examples\no_rendering_mode.py", line 1545, in game_loop
    world.render(display)
  File "C:\CarlaDReyeVR\carla\PythonAPI\examples\no_rendering_mode.py", line 1296, in render
    walkers)
  File "schematic_mode.py", line 82, in render_actors
    surface, vehicles, traffic_lights, speed_limits, walkers
  File "C:\CarlaDReyeVR\carla\PythonAPI\examples\no_rendering_mode.py", line 1243, in render_actors
    self._render_vehicles(surface, vehicles, self.map_image.world_to_pixel)
  File "C:\CarlaDReyeVR\carla\PythonAPI\examples\no_rendering_mode.py", line 1218, in _render_vehicles
    if int(v[0].attributes['number_of_wheels']) == 2:
KeyError: 'number_of_wheels'

We couldn't find any other issue with the same problem. Could you help us with this?

**Comment by GustavoSilvera** [comment]
This should be resolved with the upcoming PR (see #106)

**Comment by GustavoSilvera** [comment]
Yes, you'll want to pull these changes from the `autopilot-bugfix` temporary branch (until merged) and then rebuild the PythonAPI (`make PythonAPI`) and the new server (`make launch && make package`). 

Also in order for the new PythonAPI changes to take place, you'll need to reinstall with `pip` as described [here](https://github.com/HARPLab/DReyeVR/blob/main/Docs/Install.md#future-modifications).
