### ISSUE TITLE
"make install CARLA=../carla SR=../scenario_runner" producing errors

### ISSUE THREAD

**Issue by shh1v** [HARPLab/DReyeVR#27]
Hey! I am just installing the DReyeVR simulator and following the instructions stated in Install.MD
These are the commands I have executed:

```
mkdir CarlaDReyeVR && cd CarlaDReyeVR # doing everything in this "CarlaDReyeVR" directory
git clone https://github.com/carla-simulator/carla -b 0.9.13
cd carla
./Update.sh
mingw32-make PythonAPI && mingw32-make launch
mv /PATH/TO/SRANIPALPLUGIN/SDK/03_Unreal/Plugins/SRanipal Unreal/CarlaUE4/Plugins/ # install to carla

git clone https://github.com/HARPLab/LogitechWheelPlugin
mv LogitechWheelPlugin/LogitechWheelPlugin Unreal/CarlaUE4/Plugins/ # install to carla

cd .. 

git clone https://github.com/carla-simulator/scenario_runner -b v0.9.13

git clone https://github.com/HARPLab/DReyeVR
cd DReyeVR
```

When running `mingw32-make install CARLA=../carla SR=../scenario_runner`, I get the following output:

`Unknown filetype: E:\work\CarlaDReyeVR\DReyeVR\Content\DReyeVR_Signs\*
Traceback (most recent call last):
  File "Scripts/install.py", line 59, in <module>
    check_files=["CHANGELOG.md"],
  File "Scripts/install.py", line 46, in install_over
    advanced_cp(DReyeVR_path, advanced_join([ROOT, CARLA_path]), verbose=True)
  File "E:\work\CarlaDReyeVR\DReyeVR\Scripts\utils.py", line 248, in advanced_cp
    raise e
  File "E:\work\CarlaDReyeVR\DReyeVR\Scripts\utils.py", line 245, in advanced_cp
    advanced_cp(f, dest, verbose=verbose)
  File "E:\work\CarlaDReyeVR\DReyeVR\Scripts\utils.py", line 234, in advanced_cp
    raise Exception("Cannot copy a directory to a file")
Exception: Cannot copy a directory to a file
Makefile:9: recipe for target 'install' failed
mingw32-make: *** [install] Error 1`
The full output can be found as an attachment. I would really appreciate it if you could help me out.
[error.txt](https://github.com/HARPLab/DReyeVR/files/8736030/error.txt)

**Comment by shh1v** [comment]
It works now. Thank you so much @GustavoSilvera
